# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=30)),
                ('last_name', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=30)),
                ('usernam', models.CharField(blank=True, default='', max_length=20)),
                ('password', models.CharField(blank=True, default=' ', max_length=30)),
            ],
        ),
    ]
