# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_person_question_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Tag')),
            ],
        ),
    ]
