# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_questiontag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astatement', models.CharField(blank=True, default='', max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Person')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='statement',
            new_name='qstatement',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Question'),
        ),
    ]
