# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20180415_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('astatement',)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('Type',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('qstatement',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('Name',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name',)},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usernam',
            new_name='username',
        ),
    ]
