# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20180422_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenP', models.ImageField(upload_to=b'')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenQ', models.ImageField(upload_to=b'')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Question')),
            ],
        ),
    ]
