# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_imagenp_imagenq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenp',
            options={'ordering': ('imagenP',)},
        ),
        migrations.AlterModelOptions(
            name='imagenq',
            options={'ordering': ('imagenQ',)},
        ),
    ]
