# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20180508_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.User'),
        ),
        migrations.AlterField(
            model_name='question',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Person'),
        ),
    ]
