# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20180508_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenp',
            name='imagenP',
            field=models.ImageField(default='static/media/', upload_to='static/'),
        ),
    ]
